CREATE TABLE Route(
    id SERIAL PRIMARY KEY,
    routeName VARCHAR(255) NOT NULL
);

CREATE TABLE Stop (
    id SERIAL PRIMARY KEY,
    stopName VARCHAR(10000) NOT NULL,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION
);


CREATE TABLE BusLine(
    id SERIAL PRIMARY KEY,
    lineNumber VARCHAR(10)
);


CREATE TABLE StopRoute (
    id serial PRIMARY KEY,
    route_id int REFERENCES Route(id) ON DELETE CASCADE ON UPDATE CASCADE,
    stop_id int REFERENCES Stop(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BusLineRoute (
    id SERIAL PRIMARY KEY,
    route_id INT REFERENCES Route(id) ON DELETE CASCADE ON UPDATE CASCADE,
    busLine_id INT REFERENCES BusLine(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE StopBusLine (
    id SERIAL PRIMARY KEY,
    stop_id INT REFERENCES Stop(id) ON DELETE CASCADE ON UPDATE CASCADE,
    busLine_id INT REFERENCES BusLine(id) ON DELETE CASCADE ON UPDATE CASCADE
);
